{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4110ff3-f243-42c3-b6ba-74a855971ea4",
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset_info = dict(\n",
    "    dataset_name='horse10',\n",
    "    paper_info=dict(\n",
    "        author='Mathis, Alexander and Biasi, Thomas and '\n",
    "        'Schneider, Steffen and '\n",
    "        'Yuksekgonul, Mert and Rogers, Byron and '\n",
    "        'Bethge, Matthias and '\n",
    "        'Mathis, Mackenzie W',\n",
    "        title='Pretraining boosts out-of-domain robustness '\n",
    "        'for pose estimation',\n",
    "        container='Proceedings of the IEEE/CVF Winter Conference on '\n",
    "        'Applications of Computer Vision',\n",
    "        year='2021',\n",
    "        homepage='http://www.mackenziemathislab.org/horse10',\n",
    "    ),\n",
    "    keypoint_info={\n",
    "        0:\n",
    "        dict(name='Nose', id=0, color=[255, 153, 255], type='upper', swap=''),\n",
    "        1:\n",
    "        dict(name='Eye', id=1, color=[255, 153, 255], type='upper', swap=''),\n",
    "        2:\n",
    "        dict(\n",
    "            name='Nearknee',\n",
    "            id=2,\n",
    "            color=[255, 102, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        3:\n",
    "        dict(\n",
    "            name='Nearfrontfetlock',\n",
    "            id=3,\n",
    "            color=[255, 102, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        4:\n",
    "        dict(\n",
    "            name='Nearfrontfoot',\n",
    "            id=4,\n",
    "            color=[255, 102, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        5:\n",
    "        dict(\n",
    "            name='Offknee', id=5, color=[255, 102, 255], type='upper',\n",
    "            swap=''),\n",
    "        6:\n",
    "        dict(\n",
    "            name='Offfrontfetlock',\n",
    "            id=6,\n",
    "            color=[255, 102, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        7:\n",
    "        dict(\n",
    "            name='Offfrontfoot',\n",
    "            id=7,\n",
    "            color=[255, 102, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        8:\n",
    "        dict(\n",
    "            name='Shoulder',\n",
    "            id=8,\n",
    "            color=[255, 153, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        9:\n",
    "        dict(\n",
    "            name='Midshoulder',\n",
    "            id=9,\n",
    "            color=[255, 153, 255],\n",
    "            type='upper',\n",
    "            swap=''),\n",
    "        10:\n",
    "        dict(\n",
    "            name='Elbow', id=10, color=[255, 153, 255], type='upper', swap=''),\n",
    "        11:\n",
    "        dict(\n",
    "            name='Girth', id=11, color=[255, 153, 255], type='upper', swap=''),\n",
    "        12:\n",
    "        dict(\n",
    "            name='Wither', id=12, color=[255, 153, 255], type='upper',\n",
    "            swap=''),\n",
    "        13:\n",
    "        dict(\n",
    "            name='Nearhindhock',\n",
    "            id=13,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        14:\n",
    "        dict(\n",
    "            name='Nearhindfetlock',\n",
    "            id=14,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        15:\n",
    "        dict(\n",
    "            name='Nearhindfoot',\n",
    "            id=15,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        16:\n",
    "        dict(name='Hip', id=16, color=[255, 153, 255], type='lower', swap=''),\n",
    "        17:\n",
    "        dict(\n",
    "            name='Stifle', id=17, color=[255, 153, 255], type='lower',\n",
    "            swap=''),\n",
    "        18:\n",
    "        dict(\n",
    "            name='Offhindhock',\n",
    "            id=18,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        19:\n",
    "        dict(\n",
    "            name='Offhindfetlock',\n",
    "            id=19,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        20:\n",
    "        dict(\n",
    "            name='Offhindfoot',\n",
    "            id=20,\n",
    "            color=[255, 51, 255],\n",
    "            type='lower',\n",
    "            swap=''),\n",
    "        21:\n",
    "        dict(\n",
    "            name='Ischium',\n",
    "            id=21,\n",
    "            color=[255, 153, 255],\n",
    "            type='lower',\n",
    "            swap='')\n",
    "    },\n",
    "    skeleton_info={\n",
    "        0:\n",
    "        dict(link=('Nose', 'Eye'), id=0, color=[255, 153, 255]),\n",
    "        1:\n",
    "        dict(link=('Eye', 'Wither'), id=1, color=[255, 153, 255]),\n",
    "        2:\n",
    "        dict(link=('Wither', 'Hip'), id=2, color=[255, 153, 255]),\n",
    "        3:\n",
    "        dict(link=('Hip', 'Ischium'), id=3, color=[255, 153, 255]),\n",
    "        4:\n",
    "        dict(link=('Ischium', 'Stifle'), id=4, color=[255, 153, 255]),\n",
    "        5:\n",
    "        dict(link=('Stifle', 'Girth'), id=5, color=[255, 153, 255]),\n",
    "        6:\n",
    "        dict(link=('Girth', 'Elbow'), id=6, color=[255, 153, 255]),\n",
    "        7:\n",
    "        dict(link=('Elbow', 'Shoulder'), id=7, color=[255, 153, 255]),\n",
    "        8:\n",
    "        dict(link=('Shoulder', 'Midshoulder'), id=8, color=[255, 153, 255]),\n",
    "        9:\n",
    "        dict(link=('Midshoulder', 'Wither'), id=9, color=[255, 153, 255]),\n",
    "        10:\n",
    "        dict(\n",
    "            link=('Nearknee', 'Nearfrontfetlock'),\n",
    "            id=10,\n",
    "            color=[255, 102, 255]),\n",
    "        11:\n",
    "        dict(\n",
    "            link=('Nearfrontfetlock', 'Nearfrontfoot'),\n",
    "            id=11,\n",
    "            color=[255, 102, 255]),\n",
    "        12:\n",
    "        dict(\n",
    "            link=('Offknee', 'Offfrontfetlock'), id=12, color=[255, 102, 255]),\n",
    "        13:\n",
    "        dict(\n",
    "            link=('Offfrontfetlock', 'Offfrontfoot'),\n",
    "            id=13,\n",
    "            color=[255, 102, 255]),\n",
    "        14:\n",
    "        dict(\n",
    "            link=('Nearhindhock', 'Nearhindfetlock'),\n",
    "            id=14,\n",
    "            color=[255, 51, 255]),\n",
    "        15:\n",
    "        dict(\n",
    "            link=('Nearhindfetlock', 'Nearhindfoot'),\n",
    "            id=15,\n",
    "            color=[255, 51, 255]),\n",
    "        16:\n",
    "        dict(\n",
    "            link=('Offhindhock', 'Offhindfetlock'),\n",
    "            id=16,\n",
    "            color=[255, 51, 255]),\n",
    "        17:\n",
    "        dict(\n",
    "            link=('Offhindfetlock', 'Offhindfoot'),\n",
    "            id=17,\n",
    "            color=[255, 51, 255])\n",
    "    },\n",
    "    joint_weights=[1.] * 22,\n",
    "    sigmas=[])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
